name: Bug Report
description: Create a report to help us improve
body:
  - type: textarea
    attributes:
      label: Description
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
  - type: input
    attributes:
      label: Environment
      placeholder: OS, Python version...
